// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a DigitalOcean DNS record resource.
type DNSRecord struct {
	s *pulumi.ResourceState
}

// NewDNSRecord registers a new resource with the given unique name, arguments, and options.
func NewDNSRecord(ctx *pulumi.Context,
	name string, args *DNSRecordArgs, opts ...pulumi.ResourceOpt) (*DNSRecord, error) {
	if args == nil || args.Domain == nil {
		return nil, errors.New("missing required argument 'Domain'")
	}
	if args == nil || args.Type == nil {
		return nil, errors.New("missing required argument 'Type'")
	}
	if args == nil || args.Value == nil {
		return nil, errors.New("missing required argument 'Value'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["domain"] = nil
		inputs["flags"] = nil
		inputs["name"] = nil
		inputs["port"] = nil
		inputs["priority"] = nil
		inputs["tag"] = nil
		inputs["ttl"] = nil
		inputs["type"] = nil
		inputs["value"] = nil
		inputs["weight"] = nil
	} else {
		inputs["domain"] = args.Domain
		inputs["flags"] = args.Flags
		inputs["name"] = args.Name
		inputs["port"] = args.Port
		inputs["priority"] = args.Priority
		inputs["tag"] = args.Tag
		inputs["ttl"] = args.Ttl
		inputs["type"] = args.Type
		inputs["value"] = args.Value
		inputs["weight"] = args.Weight
	}
	inputs["fqdn"] = nil
	s, err := ctx.RegisterResource("do:core/dNSRecord:DNSRecord", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &DNSRecord{s: s}, nil
}

// GetDNSRecord gets an existing DNSRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDNSRecord(ctx *pulumi.Context,
	name string, id pulumi.ID, state *DNSRecordState, opts ...pulumi.ResourceOpt) (*DNSRecord, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["domain"] = state.Domain
		inputs["flags"] = state.Flags
		inputs["fqdn"] = state.Fqdn
		inputs["name"] = state.Name
		inputs["port"] = state.Port
		inputs["priority"] = state.Priority
		inputs["tag"] = state.Tag
		inputs["ttl"] = state.Ttl
		inputs["type"] = state.Type
		inputs["value"] = state.Value
		inputs["weight"] = state.Weight
	}
	s, err := ctx.ReadResource("do:core/dNSRecord:DNSRecord", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &DNSRecord{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *DNSRecord) URN() *pulumi.URNOutput {
	return r.s.URN
}

// ID is this resource's unique identifier assigned by its provider.
func (r *DNSRecord) ID() *pulumi.IDOutput {
	return r.s.ID
}

// The domain to add the record to
func (r *DNSRecord) Domain() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["domain"])
}

// The flags of the record (integer between 0-255), for CAA records.
func (r *DNSRecord) Flags() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["flags"])
}

// The FQDN of the record
func (r *DNSRecord) Fqdn() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["fqdn"])
}

// The name of the record
func (r *DNSRecord) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// The port of the record, for SRV records.
func (r *DNSRecord) Port() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["port"])
}

// The priority of the record, for MX and SRV
// records.
func (r *DNSRecord) Priority() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["priority"])
}

// The tag of the record (one of `issue`, `wildissue`, or `iodef`), for CAA records.
func (r *DNSRecord) Tag() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["tag"])
}

// The time to live for the record, in seconds.
func (r *DNSRecord) Ttl() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["ttl"])
}

// The type of record
func (r *DNSRecord) Type() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["type"])
}

// The value of the record
func (r *DNSRecord) Value() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["value"])
}

// The weight of the record, for SRV records.
func (r *DNSRecord) Weight() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["weight"])
}

// Input properties used for looking up and filtering DNSRecord resources.
type DNSRecordState struct {
	// The domain to add the record to
	Domain interface{}
	// The flags of the record (integer between 0-255), for CAA records.
	Flags interface{}
	// The FQDN of the record
	Fqdn interface{}
	// The name of the record
	Name interface{}
	// The port of the record, for SRV records.
	Port interface{}
	// The priority of the record, for MX and SRV
	// records.
	Priority interface{}
	// The tag of the record (one of `issue`, `wildissue`, or `iodef`), for CAA records.
	Tag interface{}
	// The time to live for the record, in seconds.
	Ttl interface{}
	// The type of record
	Type interface{}
	// The value of the record
	Value interface{}
	// The weight of the record, for SRV records.
	Weight interface{}
}

// The set of arguments for constructing a DNSRecord resource.
type DNSRecordArgs struct {
	// The domain to add the record to
	Domain interface{}
	// The flags of the record (integer between 0-255), for CAA records.
	Flags interface{}
	// The name of the record
	Name interface{}
	// The port of the record, for SRV records.
	Port interface{}
	// The priority of the record, for MX and SRV
	// records.
	Priority interface{}
	// The tag of the record (one of `issue`, `wildissue`, or `iodef`), for CAA records.
	Tag interface{}
	// The time to live for the record, in seconds.
	Ttl interface{}
	// The type of record
	Type interface{}
	// The value of the record
	Value interface{}
	// The weight of the record, for SRV records.
	Weight interface{}
}
