// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a DigitalOcean Floating IP to represent a publicly-accessible static IP addresses that can be mapped to one of your Droplets.
type FloatingIP struct {
	s *pulumi.ResourceState
}

// NewFloatingIP registers a new resource with the given unique name, arguments, and options.
func NewFloatingIP(ctx *pulumi.Context,
	name string, args *FloatingIPArgs, opts ...pulumi.ResourceOpt) (*FloatingIP, error) {
	if args == nil || args.Region == nil {
		return nil, errors.New("missing required argument 'Region'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["dropletId"] = nil
		inputs["ipAddress"] = nil
		inputs["region"] = nil
	} else {
		inputs["dropletId"] = args.DropletId
		inputs["ipAddress"] = args.IpAddress
		inputs["region"] = args.Region
	}
	s, err := ctx.RegisterResource("do:core/floatingIP:FloatingIP", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &FloatingIP{s: s}, nil
}

// GetFloatingIP gets an existing FloatingIP resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFloatingIP(ctx *pulumi.Context,
	name string, id pulumi.ID, state *FloatingIPState, opts ...pulumi.ResourceOpt) (*FloatingIP, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["dropletId"] = state.DropletId
		inputs["ipAddress"] = state.IpAddress
		inputs["region"] = state.Region
	}
	s, err := ctx.ReadResource("do:core/floatingIP:FloatingIP", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &FloatingIP{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *FloatingIP) URN() *pulumi.URNOutput {
	return r.s.URN
}

// ID is this resource's unique identifier assigned by its provider.
func (r *FloatingIP) ID() *pulumi.IDOutput {
	return r.s.ID
}

// The ID of Droplet that the Floating IP will be assigned to.
func (r *FloatingIP) DropletId() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["dropletId"])
}

// The IP Address of the resource
func (r *FloatingIP) IpAddress() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["ipAddress"])
}

// The region that the Floating IP is reserved to.
func (r *FloatingIP) Region() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["region"])
}

// Input properties used for looking up and filtering FloatingIP resources.
type FloatingIPState struct {
	// The ID of Droplet that the Floating IP will be assigned to.
	DropletId interface{}
	// The IP Address of the resource
	IpAddress interface{}
	// The region that the Floating IP is reserved to.
	Region interface{}
}

// The set of arguments for constructing a FloatingIP resource.
type FloatingIPArgs struct {
	// The ID of Droplet that the Floating IP will be assigned to.
	DropletId interface{}
	// The IP Address of the resource
	IpAddress interface{}
	// The region that the Floating IP is reserved to.
	Region interface{}
}
