// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupCertificate(ctx *pulumi.Context, args *GetCertificateArgs) (*GetCertificateResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("do:core/getCertificate:getCertificate", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCertificateResult{
		Domains: outputs["domains"],
		NotAfter: outputs["notAfter"],
		Sha1Fingerprint: outputs["sha1Fingerprint"],
		State: outputs["state"],
		Type: outputs["type"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCertificate.
type GetCertificateArgs struct {
	Name interface{}
}

// A collection of values returned by getCertificate.
type GetCertificateResult struct {
	Domains interface{}
	NotAfter interface{}
	Sha1Fingerprint interface{}
	State interface{}
	Type interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
