// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupFloatingIP(ctx *pulumi.Context, args *GetFloatingIPArgs) (*GetFloatingIPResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["ipAddress"] = args.IpAddress
	}
	outputs, err := ctx.Invoke("do:core/getFloatingIP:getFloatingIP", inputs)
	if err != nil {
		return nil, err
	}
	return &GetFloatingIPResult{
		DropletId: outputs["dropletId"],
		Region: outputs["region"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getFloatingIP.
type GetFloatingIPArgs struct {
	IpAddress interface{}
}

// A collection of values returned by getFloatingIP.
type GetFloatingIPResult struct {
	DropletId interface{}
	Region interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
