// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupLoadBalancer(ctx *pulumi.Context, args *GetLoadBalancerArgs) (*GetLoadBalancerResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("do:core/getLoadBalancer:getLoadBalancer", inputs)
	if err != nil {
		return nil, err
	}
	return &GetLoadBalancerResult{
		Algorithm: outputs["algorithm"],
		DropletIds: outputs["dropletIds"],
		DropletTag: outputs["dropletTag"],
		ForwardingRules: outputs["forwardingRules"],
		Healthcheck: outputs["healthcheck"],
		Ip: outputs["ip"],
		RedirectHttpToHttps: outputs["redirectHttpToHttps"],
		Region: outputs["region"],
		Status: outputs["status"],
		StickySessions: outputs["stickySessions"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getLoadBalancer.
type GetLoadBalancerArgs struct {
	Name interface{}
}

// A collection of values returned by getLoadBalancer.
type GetLoadBalancerResult struct {
	Algorithm interface{}
	DropletIds interface{}
	DropletTag interface{}
	ForwardingRules interface{}
	Healthcheck interface{}
	Ip interface{}
	RedirectHttpToHttps interface{}
	Region interface{}
	Status interface{}
	StickySessions interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
