// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupSSHKey(ctx *pulumi.Context, args *GetSSHKeyArgs) (*GetSSHKeyResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("do:core/getSSHKey:getSSHKey", inputs)
	if err != nil {
		return nil, err
	}
	return &GetSSHKeyResult{
		Fingerprint: outputs["fingerprint"],
		PublicKey: outputs["publicKey"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getSSHKey.
type GetSSHKeyArgs struct {
	Name interface{}
}

// A collection of values returned by getSSHKey.
type GetSSHKeyResult struct {
	Fingerprint interface{}
	PublicKey interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
