// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupTag(ctx *pulumi.Context, args *GetTagArgs) (*GetTagResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("do:core/getTag:getTag", inputs)
	if err != nil {
		return nil, err
	}
	return &GetTagResult{
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getTag.
type GetTagArgs struct {
	Name interface{}
}

// A collection of values returned by getTag.
type GetTagResult struct {
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
