// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package core

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupVolumeSnapshot(ctx *pulumi.Context, args *GetVolumeSnapshotArgs) (*GetVolumeSnapshotResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["mostRecent"] = args.MostRecent
		inputs["name"] = args.Name
		inputs["nameRegex"] = args.NameRegex
		inputs["region"] = args.Region
	}
	outputs, err := ctx.Invoke("do:core/getVolumeSnapshot:getVolumeSnapshot", inputs)
	if err != nil {
		return nil, err
	}
	return &GetVolumeSnapshotResult{
		CreatedAt: outputs["createdAt"],
		MinDiskSize: outputs["minDiskSize"],
		Regions: outputs["regions"],
		Size: outputs["size"],
		VolumeId: outputs["volumeId"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getVolumeSnapshot.
type GetVolumeSnapshotArgs struct {
	MostRecent interface{}
	Name interface{}
	NameRegex interface{}
	Region interface{}
}

// A collection of values returned by getVolumeSnapshot.
type GetVolumeSnapshotResult struct {
	CreatedAt interface{}
	MinDiskSize interface{}
	Regions interface{}
	Size interface{}
	VolumeId interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
