// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getDroplet(args: GetDropletArgs, opts?: pulumi.InvokeOptions): Promise<GetDropletResult> {
    return pulumi.runtime.invoke("do:core/getDroplet:getDroplet", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDroplet.
 */
export interface GetDropletArgs {
    readonly name: string;
}

/**
 * A collection of values returned by getDroplet.
 */
export interface GetDropletResult {
    readonly backups: boolean;
    readonly disk: number;
    readonly image: string;
    readonly ipv4Address: string;
    readonly ipv4AddressPrivate: string;
    readonly ipv6: boolean;
    readonly ipv6Address: string;
    readonly ipv6AddressPrivate: string;
    readonly locked: boolean;
    readonly memory: number;
    readonly monitoring: boolean;
    readonly priceHourly: number;
    readonly priceMonthly: number;
    readonly privateNetworking: boolean;
    readonly region: string;
    readonly size: string;
    readonly status: string;
    readonly tags: string[];
    readonly vcpus: number;
    readonly volumeIds: string[];
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
