// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Get information on a DNS record. This data source provides the name, TTL, and zone
 * file as configured on your Digital Ocean account. This is useful if the record
 * in question is not managed by Terraform.
 * 
 * An error is triggered if the provided domain name or record are not managed with
 * your Digital Ocean account.
 */
export function getDNSRecord(args: GetDNSRecordArgs, opts?: pulumi.InvokeOptions): Promise<GetDNSRecordResult> {
    return pulumi.runtime.invoke("do:core/getDNSRecord:getDNSRecord", {
        "domain": args.domain,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDNSRecord.
 */
export interface GetDNSRecordArgs {
    /**
     * The domain name of the record.
     */
    readonly domain: string;
    /**
     * The name of the record.
     */
    readonly name: string;
}

/**
 * A collection of values returned by getDNSRecord.
 */
export interface GetDNSRecordResult {
    readonly data: string;
    readonly flags: number;
    readonly port: number;
    readonly priority: number;
    readonly tag: string;
    readonly ttl: number;
    readonly type: string;
    readonly weight: number;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
