// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getSSHKey(args: GetSSHKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSSHKeyResult> {
    return pulumi.runtime.invoke("do:core/getSSHKey:getSSHKey", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSSHKey.
 */
export interface GetSSHKeyArgs {
    readonly name: string;
}

/**
 * A collection of values returned by getSSHKey.
 */
export interface GetSSHKeyResult {
    readonly fingerprint: string;
    readonly publicKey: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
