// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

// The token key for API operations.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "do:token")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "DO_TOKEN", "DIGITAL_OCEAN_TOKEN", "DIGITALOCEAN_TOKEN").(string); ok {
		return dv
	}
	panic(err.Error())
	return v
}
