# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

__config__ = pulumi.Config('do')

token = utilities.require_with_default(lambda: __config__.require('token'), utilities.get_env('DO_TOKEN', 'DIGITAL_OCEAN_TOKEN', 'DIGITALOCEAN_TOKEN'))
"""
The token key for API operations.
"""

