# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class GetFloatingIPResult(object):
    """
    A collection of values returned by getFloatingIP.
    """
    def __init__(__self__, droplet_id=None, region=None, id=None):
        if droplet_id and not isinstance(droplet_id, int):
            raise TypeError('Expected argument droplet_id to be a int')
        __self__.droplet_id = droplet_id
        if region and not isinstance(region, basestring):
            raise TypeError('Expected argument region to be a basestring')
        __self__.region = region
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_floating_ip(ip_address=None):
    __args__ = dict()

    __args__['ipAddress'] = ip_address
    __ret__ = pulumi.runtime.invoke('do:core/getFloatingIP:getFloatingIP', __args__)

    return GetFloatingIPResult(
        droplet_id=__ret__.get('dropletId'),
        region=__ret__.get('region'),
        id=__ret__.get('id'))
