# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class GetVolumeResult(object):
    """
    A collection of values returned by getVolume.
    """
    def __init__(__self__, droplet_ids=None, filesystem_label=None, filesystem_type=None, size=None, id=None):
        if droplet_ids and not isinstance(droplet_ids, list):
            raise TypeError('Expected argument droplet_ids to be a list')
        __self__.droplet_ids = droplet_ids
        if filesystem_label and not isinstance(filesystem_label, basestring):
            raise TypeError('Expected argument filesystem_label to be a basestring')
        __self__.filesystem_label = filesystem_label
        if filesystem_type and not isinstance(filesystem_type, basestring):
            raise TypeError('Expected argument filesystem_type to be a basestring')
        __self__.filesystem_type = filesystem_type
        if size and not isinstance(size, int):
            raise TypeError('Expected argument size to be a int')
        __self__.size = size
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_volume(description=None, name=None, region=None):
    __args__ = dict()

    __args__['description'] = description
    __args__['name'] = name
    __args__['region'] = region
    __ret__ = pulumi.runtime.invoke('do:core/getVolume:getVolume', __args__)

    return GetVolumeResult(
        droplet_ids=__ret__.get('dropletIds'),
        filesystem_label=__ret__.get('filesystemLabel'),
        filesystem_type=__ret__.get('filesystemType'),
        size=__ret__.get('size'),
        id=__ret__.get('id'))
